### ISSUE TITLE
The distinguishable rule seems limiting

### ISSUE THREAD

**Issue by paldepind** [AFASSoftware/maquette#12]
Due to the distinguishable rule I can't do stuff like this:

```javascript
h('div', [
  h('span', ['Hello world']),
  h('span', ['Oh no!'])
]);
```

That seems very limiting and other virtual DOM libraries does not have the same restriction.

The tutorial was quite fun :)

**Comment by johan-gorter** [comment]
I agree that the distinguishable rule makes developing an application using maquette a little bit more complicated compared to other virtual DOM frameworks.

Your example only needs an extra key property to work.

The distinguishable rule is there for two main reasons:

 - Maquette can do the right animation when nodes change. It knows if a node has been replaced or if it has changed.
 - Maquette can perform diffing faster, because iterating the old properties is not neccessary

If you care about animations, I think the little extra effort is a small price to pay.

**Comment by paldepind** [comment]
> Maquette can do the right animation when nodes change. It knows if a node has been replaced or if it has changed.

The thing is, in the cases where this is an issue you're not doing any reordering. In other virtual DOM libraries keys are optional and you can add them when it makes sense. For instance when you're rendering a list of elements where elements might get added, removed or moved. And in those cases finding a key is often straightforward because you're rendering something with a unique identifier anyway.

But if I'm simply doing this:

```javascript
h('div', [
  h('p', ['This is the first paragraph.']),
  h('p', ['And I'm the second!'])
]);
```

Then I don't care about animations and I don't have any natural keys because I'm just doing a static view. Having to invent a random key for a static paragraph feels very unnatural.

> Maquette can perform diffing faster, because iterating the old properties is not neccessary

Other libraries seems to be doing just fine performance wise without requiring uniqueness for _every_ element.

**Comment by johan-gorter** [comment]
I know the extra keys are sometimes annoying, We have used maquette enough to experience this ourselves.

I think it is importan to prevent people from accidentally updating event handlers on every render. If an inexperienced user uses an anonymous function as an event handler, every renderMaquette would update the real DOM. This is why maquette disallows changing event handlers.

So if you were now to update the virtual DOM
  
    h("div", [
      h("button", {onclick: handlePrevious}, "Previous"),
      h("button", {onclick: handleNext}, "Next")
    ])

with 

    h("div", [
      h("button", {onclick: handlePrevious}, "Previous"),
      h("button", {onclick: handleFinish}, "Finish")
    ])

you would accidentally trigger such an event handler update. If you were to use animations, you would also not see the next button disappear and the finish button appear, because they are morphed into each other.

Forcing a user to use keys to make the buttons distinguishable alleviates most of this problem.

I think if I give it some more thought, that I can come up with a solution that makes distinguishable children required less often. It is always easier to make the rules more lenient than to make them stricter. I will leave this issue open until I can come up with a good solution.

**Comment by paldepind** [comment]
The main thing I think you should consider is that people will be comparing Maquette to other libraries that does not have this restriction. So you need a good explanation in the documentation or people will see Maquette as inferior.

**Comment by johan-gorter** [comment]
I have made the distinguishable rule less strict and I documented the two other special rules as well on http://maquettejs.org/docs/rules.html
