### ISSUE TITLE
Diff algorithm turns reorderings into removals and additions

### ISSUE THREAD

**Issue by paldepind** [AFASSoftware/maquette#13]
How am I supposed to do sensible animations when moving children actually doesn't move the DOM nodes around but instead triggers a series of creations and removals?

**Comment by johan-gorter** [comment]
Reordering is currently implemented in maquette as a series of adds and removes. If you want to animate reordering, you could track the items being removed and added and reconstruct a moving animation from there.

If maquette was to move the dom node to the new index, would that make it easier for you to animate the move?

**Comment by paldepind** [comment]
I was just going through your diffing algorithm and was quite surprised to see that you don't detect reordering at all.

I think you should either change that or add to the documentation that the enter and remove animations are also being triggered on reordering.

I can appreciate the simplicity of the current algorithm though.

**Comment by johan-gorter** [comment]
One of the important aspects of maquette is the ability to do animations. If maquette were to detect reordering and reorder the DOM nodes, adding an animation would become very hard to do, because the old location would need a temporary placeholder which would then gradually diminish.

Making an animation by reconstructing moves from enter and exit animations would be easier in my opinion. I will make a demo of this when I have the time.

**Comment by paldepind** [comment]
Yes. It is certainly easier to create animations if one animates reorderings as enters and exits. But it is a simplification.

Consider a case where I animate enters and exits as fade in and fade outs. But, I also want to animate reorderings simply as the elements moving around. You cannot do that with Maquette.

Your approach is fine for some use cases. The most important thing is to document it. Mention that the add/remove animations will also be triggered for reordering. I discovered it by reading the source code. But if I had discovered it in development I would have been very confused.

Full disclosure: I'm considering creating my own virtual DOM library. So do what you think is best for your library!

**Comment by localvoid** [comment]
It is also important to generate minimal number of move operations for move animations. There are also cases like "hero transition" animations, to implement them virtual dom library should support moving nodes from one subtree to another.

**Comment by johan-gorter** [comment]
I read up on the "hero transition". From the sample code on https://www.polymer-project.org/0.5/docs/elements/core-animated-pages.html I see that a hero can even be moved into another parent element. This is more than just reordering. 

I think it would not be a problem to recreate the hero DOM on the new location and then moving it using a translate() animation from the old location.

**Comment by paldepind** [comment]
> to implement them virtual dom library should support moving nodes from one subtree to another.

I think that is a rare case in practice. And it would increase the complexity of the algorithm drastically (as far as I remember general algorithms for finding the shortest tree edit distance are O(n^3)) which would reduce performance in all cases.

**Comment by localvoid** [comment]
@johan-gorter if node represents a stateful Component, it will lose internal state.

@paldepind it is actually quite easy, just create a special virtual node that will move html node if it is already have reference to it. I am using similar technique to preserve state for IME when I am changing text around cursor (real-time collaborative editor).

**Comment by paldepind** [comment]
@localvoid Please explain. How does the special virtual node get moved around? How does it determine if it already has reference for the DOM node? Does any virtual DOM library use such a technique? I've not seen it.

**Comment by johan-gorter** [comment]
@localvoid Maquette itself does not know the concept of compontents, components are just a best practice, as I explained in http://maquettejs.org/docs/component-approach.html 

If you use this best practice, you are responsible for managing the components yourself and so they do not lose state if they are not being rendered or being moved.

**Comment by localvoid** [comment]
@paldepind Just store reference to the virtual node that itself has reference to the real node, and reuse it on rerender. Yes, there are vdom libraries that cover such cases.

@johan-gorter vdom library is responsible for moving nodes, if it can't perform move on virtual nodes and instead recreates it, it will lose its state, it is as simple as that.

**Comment by paldepind** [comment]
@localvoid 

> Just store reference to the virtual node that itself has reference to the real node, and reuse it on rerender.

Yes, storing created DOM nodes in the virtual DOM tree is common. You can then reuse the virtual DOM tree as the old virtual tree in your next diff/update and the library can avoid traversing the real DOM tree.

But reusing those old virtual DOM nodes as the new nodes passed to the next update seems odd. Then the user would manually have to modify the virtual DOM nodes he passed to the last update which pretty much destroys the benefits of having a virtual DOM. Now you're just manually modifying the virtual DOM instead of manually modifying the real DOM. And the library doesn't really handle the moves – it just lets the user do it.

> Yes, there are vdom libraries that cover such cases.

Please name them.

**Comment by localvoid** [comment]
@paldepind 

>You can then reuse the virtual DOM tree as the old virtual tree in your next diff/update and the library can avoid traversing the real DOM tree.

There are much more important reasons why it is useful to store refs in vdom tree, especially if vdom library deals with animations.

>Then the user would manually have to modify the virtual DOM nodes he passed to the last update which pretty much destroys the benefits of having a virtual DOM.

```
if (this._captureHeroNode == null) {
  this._captureHeroNode = new CaptureNode();
}
return (<div>{this._captureHeroNode.capture(new HeroNode())}</div>);
```

>Please name them.

https://github.com/localvoid/vdom

**Comment by paldepind** [comment]
> There are much more important reasons why it is useful to store refs in vdom tree, especially if vdom library deals with animations.

Yes, animating is another great reason. What other reasons are you thinking about?

> https://github.com/localvoid/vdom

Thank you. Why don't you have vdom in the virtual DOM benchmarks?

**Comment by localvoid** [comment]
>Yes, animating is another great reason. What other reasons are you thinking about?

- good diff/patch algorithm for children is so much easier to implement, after update phase all nodes in the new list will store references to the real nodes from old list, so we can just go from right to left and use refs from new children list for `insertBefore` operations to perform moves, and inserts.
- accessing real html nodes, components is also easier, just store refs to virtual nodes.

>Thank you. Why don't you have vdom in the virtual DOM benchmarks?

There was too much libraries written by me in this benchmark, so when maquette were added to this benchmark, I've removed vdom :) It is flexible, and covers many use cases but it is not one of the fastest implementations, especially in real applications it will be slower because virtual nodes are polymorphic and hot code path for children reconcilliation will be deoptimized to megamorphic cases.
Right now I think that it is better to write vdom library, so that vnodes are monomorphic and just cover all important use cases in the vdom library.

**Comment by paldepind** [comment]
Yes. I have observed the same and agree on both on your reasons. But those reasons are not "much more important". Actually I think they are very closely connected to my remark about not having to traverse the real DOM tree. You get all of these benefits because you have a JavaScript data structure that gives easy and efficient access to the DOM.

> virtual nodes are polymorphic and hot code path for children reconcilliation will be deoptimized to megamorphic cases.

In cito.js virtual nodes are polymorphic. They can be objects of very different structure and even string. Yet it is one of the fastest virtual DOM libraries. Maquette on the other hand uses a monomorphic vnode object with the same structure in all cases. Yet it is not among the fastest. Are you really sure that this makes a huge actual difference? Or are you talking about something else?

Btw, as I mentioned above I'm working on my own virtual DOM library. Stay on your toes! ;) :)

**Comment by localvoid** [comment]
>You get all of these benefits because you have a JavaScript data structure that gives easy and efficient access to the DOM.

I think that the current version of Bobril creates additional CacheNodes that store references to html nodes, but it doesn't store refs in virtual dom nodes, so it is possible to traverse through dom in a fast way and reuse virtual nodes (some form of optimization). I have similar implementations in separate branches of kivi, and uix libraries, but I think that storing refs in virtual nodes is more important than this kind of optimization.

>In cito.js virtual nodes are polymorphic. They can be objects of very different structure and even string. Yet it is one of the fastest virtual DOM libraries.

It is actually hard to compare performance based on this benchmark, this benchmark is all about simple children mutations, and it was created so that I could improve my vdom library :) It is probably doesn't trigger megamorphic deoptimizations in tested libraries. And if I am not wrong, cito doesn't have proper support for implementing Components on top of it, so it isn't fair to compare it with other libraries, because Components is extremely important for good vdom library.

>Are you really sure that this makes a huge actual difference?

It is not a huge difference, and I am not sure, because I don't have any good benchmark to prove this :)

When I was experimenting with kivi library, I've also tried to implement monomorphic Components(really ugly API) and it was really fast in dbmonster benchmark :) Right now, it is just monomorphic virtual nodes and polymorphic components.

**Comment by paldepind** [comment]
> It is actually hard to compare performance based on this benchmark, this benchmark is all about simple children mutations

Yes. I did notice that. That's a somewhat limited thing to test. Are you considering adding tests for additional things? One idea: a test where a single node in a huge tree is modified – very relevant to real world usage.

> It is probably doesn't trigger megamorphic deoptimizations in tested libraries.

Can you point towards additional detail about this form of optimizations? It's something I've worried about, but I've not been able to find much information about it.

> And if I am not wrong, cito doesn't have proper support for implementing Components on top of it, so it isn't fair to compare it with other libraries, because Components is extremely important for good vdom library.

It's readme talks a lot about it and implies that a component system will be implemented on top of the current vdom implementation.

When you say components, do you mean a type of nodes that carry state and can control their own re-rendering? I'm asking because it seems that different people mean slightly different things with the word.

Thanks for sharing your experience on virtual DOM libraries :)

**Comment by johan-gorter** [comment]
I stopped optimizing maquette, because it could already diff thousands of nodes on all modern devices within 16ms. Optimizing further would not be noticable to end-users. We are already using maquette in a production-ready application at AFASSoftware by the way.

@localvoid  I thought I had implemented vnodes to be monomorphic correctly, why do you think/know that it is not monomorphic?

@paldepind The maquette implementation assumes that vnode objects are immutable, so keeping a reference to it is only allowed to indicate that a subtree did not change. I have done this to make caching possible. We never used this by the way, because as I was saying, maquette is already fast enough.

**Comment by localvoid** [comment]
@johan-gorter sorry for misunderstanding, I was talking about my vdom library in this context. It is using polymorphic virtual nodes, all methods like (attached, detached, create, render, update, etc can be overriden) and it is probably slower than maquette, but it is very flexible.

**Comment by paldepind** [comment]
> The maquette implementation assumes that vnode objects are immutable, so keeping a reference to it is only allowed to indicate that a subtree did not change. I have done this to make caching possible. We never used this by the way, because as I was saying, maquette is already fast enough.

No. Not immutable. You modify them internally. I it would be more correct to say that the implementation assumes that _the user_ will not mutate vnodes after creation.

**Comment by johan-gorter** [comment]
@paldepind You are correct, maquette modifies the .domNode property and assumes that the user will not mutate the vnode anymore after passing it to maquette.

**Comment by localvoid** [comment]
@paldepind

>Are you considering adding tests for additional things? One idea: a test where a single node in a huge tree is modified – very relevant to real world usage.

No, I am not planning to add any tests. All vdom implementations are fast enough for most real-world use cases, most of the time DOM/reflow/repaint will be a bottleneck.

>Can you point towards additional detail about this form of optimizations? It's something I've worried about, but I've not been able to find much information about it.

http://mrale.ph/blog/2015/01/11/whats-up-with-monomorphism.html

>When you say components, do you mean a type of nodes that carry state and can control their own re-rendering? I'm asking because it seems that different people mean slightly different things with the word.

Yes, Components should be able to carry state, and have lifecycle methods like attached/detached/etc.

**Comment by paldepind** [comment]
> All vdom implementations are fast enough for most real-world use cases, most of the time DOM/reflow/repaint will be a bottleneck.

Sure. But optimizing DOM operations is also a responsibility of the virtual DOM library. Also, if it comes without drawbacks better performance is always nice.

**Comment by johan-gorter** [comment]
Coming back to how this discussion started, reorderings becoming additions and removals. This is actually an advantage when doing animations. I created a demo at http://johan-gorter.github.io/maquette-demo-hero/ showing how to do hero-transitions with maquette. I believe that this would have been much harder to do if maquette were to reorder the DOM nodes. I would really like to see hero-animations done with a library that reorders DOM nodes.

As for handling stateful components being reordered, I am still studying on how maquette should support this scenario.

**Comment by paldepind** [comment]
@johan-gorter I have not yet looked closely at your hero animation example. But at a first glance it looks quite impressive. Could you please explain why you think not having reordering is an advantage?

I have with my own virtual DOM library (which does reordering) implemented the type of animation I think you'd have a hard time doing without reorderings. [You can look at the example here](http://paldepind.github.io/snabbdom/examples/reorder-animation/).

Notice a few things:

* The animation when an element enters the DOM (press the add button)
* The different animation when an element leaves the DOM (press one of the red crosses)
* The a smooth animation when elements are reordered. This reordering animation has nothing to do with the enter and leave animation (try changing the sort)
* The animated elements are of different heights

I think (but would love to be proved wrong) that you'd have a hard time implementing this with Maquette. Both because you don't detect reorderings but also because you don't have a callback for when an element has been added into the actual DOM (you only have an event for when an element is added into it's parent).

**Comment by paldepind** [comment]
Oh. And btw, if your curious you can find my virtual DOM library [here](https://github.com/paldepind/snabbdom). All the basics are there but I still need a few more nice features :)

**Comment by johan-gorter** [comment]
Hello,

I studied your example. Very interesting work!

I have not yet seen the technique which combines reordering DOM nodes with translateY.

The hero demonstration achieves the exact same kind of reordering animation, but in a totally different way. I did not use reordering, because I wanted a placeholder to be left behind in the old location that can shrink slowly. You have solved the same problem by adding a translateY to every row.

The hero demonstration uses javascript to find the old coordinates of the exited element and creates a transition from the old coordinates to the new coordinates. It is admittedly more complex, but it is also more versitile. When navigating to a detail-page, the same technique moves the hero-elements to the new location on a totally different page.

Regarding your remark about the callback. When using appendToDom or mergeDom in maquette, the parent node is already present in the real DOM, so the afterCreate callback comes at a time the element is already in the document (very useful for adding a google maps widget or ckeditor for example). Creating the new DOM offscreen and adding it later to the document has not proven to be much more performant (anymore).

Keep up the good work.

**Comment by paldepind** [comment]
Hi again

> I studied your example. Very interesting work!

Thank you.

> I have not yet seen the technique which combines reordering DOM nodes with translateY.

I've thought it up myself ;)

> I did not use reordering, because I wanted a placeholder to be left behind in the old location that can shrink slowly.

Yes. And that is one problem I see with your approach. You're animating the _height_ of the disappearing element. Generally animating heights are very convenient but also very slow! Especially on mobile. I've very carefully designed my example so that the reordering can work by only animating `transform`. Which is the fastest thing to animate.

> The hero demonstration uses javascript to find the old coordinates of the exited element and creates a transition from the old coordinates to the new coordinates. It is admittedly more complex, but it is also more versitile. When navigating to a detail-page, the same technique moves the hero-elements to the new location on a totally different page.

I've now had the time to take a look at your hero example. I really like it. And you use `transform` to animate added heroes which is fast. For reordering of list items I much prefer my method. Both because it avoids removing elements just to recreate exact copies of them and because it does not rely on animating `height`. But as you noted my method does not handle hero animations. To do that I'd have to implement something similar to what you've got!

> Regarding your remark about the callback. When using appendToDom or mergeDom in maquette, the parent node is already present in the real DOM, so the afterCreate callback comes at a time the element is already in the document (very useful for adding a google maps widget or ckeditor for example).

Yes! You're right. My bad. You pass the parent node to your `createDom` so that it can attach the element it creates to the parent before triggering the enter hook. My virtual DOM library works slightly different. I like your approach. But there might still be cases it doesn't handle. My virtual DOM library has a insert hook that fires on an element after _all_ other elements have been inserted in the given render turn. This guarantees that any positions returned by `getBoundingClientRect` will be completely final. When your enter hook fires on an element all its following siblings will not have been added to the DOM (right?). So if I use `flex-direction: row-reverse` the position returned by `getBoundingClientRect` will not be correct. But it's a rare case so it's probably not an actual problem.

**Comment by johan-gorter** [comment]
Thanks for your comments. I also think that calling getBoundingClientRect should be used with care, because interleaving DOM updates and DOM measurements causes a browser to do reflows. And you never want the number of reflows to be influenced by the number of items on the screen.

**Comment by paldepind** [comment]
Yes. But if you do all your `getBoundingClientRect` in directly after each other only one reflow will be forced. That is exactly what my `insert` callback provides. It is triggered after all elements have been added to the DOM. So if you do the `getBoundingClientRect`s you need in that hook the reflows will be kept to a minimum. I'd much rather trigger a _single_ reflow when elements are added rather than animating `height` which reflows like crazy.

**Comment by johan-gorter** [comment]
I said I would come back to the stateful component functionality. I know how React handles this, and I chose another path with maquette.

The main reason for this is that we have found some usecases where we want state to be preserved although the component is not rendered in the DOM. 

One example is a modal dialog on a mobile screen. Here the underlying screen with state will be removed from the DOM using an animation.

Another example is our implementation of an infinite scrolling list, where we only want to render the DOM nodes that are visible through the viewport. State (multi-select checkboxes for example) must be preserved here also.

I came up with the following solution, which I added as a news item: http://maquettejs.org/2015/05/24/Different-approach-to-stateful-components.html
