### ISSUE TITLE
First-class support for progressive enhancement?

### ISSUE THREAD

**Issue by bitinn** [AFASSoftware/maquette#14]
I have been using `virtual-dom` for several months, before discovering `maquette`. As mentioned in your blog post, this module appears to use similar hypersrcipt implementation, while giving first-class support for PE?

But looking at the introduction:
http://maquettejs.org/2015/02/28/Progressive-enhancement.html

and source code at:
http://maquettejs.org/tutorial/01-intro.html

I still haven't fully understand what happens when you do a [mergeDom](https://github.com/AFASSoftware/maquette/blob/master/docs/API.md#maquettemergedom).

To put it in simpler context, let's say, we have this render template:

```
h('body', [
  h('h1', 'welcome')
]);
```

which server-rendered and output as:

```
<body>
  <h1>welcome</h1>
<body>
```

What does it take to swap it with a maquette-rendered dom using the same template? What happen when you trying to replace them, do nothing happen, or do everything get replaced like `replaceChild`.

----

As a side-note: just how similar are `maquette` and `virtual-dom` in terms of their hypersrcipt implementation?

https://github.com/Matt-Esch/virtual-dom/tree/master/virtual-hyperscript 

I am wondering if I had to rewrite https://github.com/nthtran/vdom-to-html to support `maquette`.

**Comment by johan-gorter** [comment]
Hello,

I see you are trying to render HTML on the server, a technique sometimes called isomorphic Javascript. Isomorphic Javascript was invented because it takes such a long time before React is downloaded and able to start the virtual DOM on the client.

Maquette is much faster to download and execute than React, so this makes isomorphic Javascript unnecessary imho. I have never used maquette on the server, but it it certainly possible.

The idea of progressive enhancement in maquette is that static markup from the server can be enriched with dynamic functionality on the client. 

The plans to make progressive enhancement a first-class citizen are getting more concrete, It will probably be added soon.

The hyperscript that maquette uses is very much like the one virtual-dom uses. maquette does however not support selectors with brackets, like `input[type='text']`. Maquette also uses a different syntax to add css classes dynamically, it uses the `classes` property like so: `h("div", {classes:{important:true, silly:false}})`. This notation is usually easier to use than string concatenation of a `class` or `className` property.

finally: mergeDom uses the provided real DOM node and applies the properties and adds children from the virtual DOM. The root-node from the virtual DOM tree is thus merged with the real DOM node. Children already present on the real DOM are not removed in this process.

Hope this answers your question. Can I ask what you are trying to achieve by using virtual DOM on the server?

**Comment by bitinn** [comment]
Thx for the reply. Just want to follow up on a few topcis:

1. Isomorphic, yes, though we use it due to different reasons. Server-render is good for content-focus site (say a news network) whether you have large javascript build or not. In the spirit of Progressive Enhancement, HTML and CSS are a lot more fault-tolerant than JS. Another reason is to share templates betweend frontend and backend, but that's more of a developer wish :)

2. Looking at your description it appears PE in `maquette` is for performance, let server render the static layout, and let `maquette` fill in the rest. So the core content still depends on `maquette`, and server don't render them on first-page.

3. The difficult part about mixing client-side render with server-side render, is when to attach events, and how to reuse existing dom. `virtual-dom` is still buggy in this aspect, and `React` is probably the only working one.

**Comment by aMarCruz** [comment]
This is interesting.
@johan-gorter are you comparing the vdom with the real dom element, or are you taking the actual dom as immutable and uses 2 vdom (old and new) in the comparison?

I think if the comparison is with the real dom, and dom has too much data, merging would be inefficient.

**Comment by johan-gorter** [comment]
I built progressive enhancement, because I wanted to use html and markdown for the static parts of the site, and maquette for the dynamic part. This is for two reasons:

- HTML and Markdown are easier to write than hyperscript, when it comes to longer sentences
- The static parts are valuable to search engines (SEO)

If you are using maquette to render html on the server, your best option is to clear document.body and call mergeDom to rebuild it completely on the client.

Reusing the real DOM sounds like an interesting idea. This would save some performance and preserve the focus.

**Comment by johan-gorter** [comment]
@aMarCruz The real DOM is left alone, only the enhanced parts are being compared.

**Comment by bitinn** [comment]
Cheers, that's all I needed to know :)

**Comment by doublerebel** [comment]
I would also like this feature.  It's great for:
* SEO
* mobile load times
* customers who like NoScript
* accessibility
* code reuse

I create my templates with Jade/Pug and then compile them into hyperscript.  Server-side I can already render Jade/Pug templates directly, and I use the same Models for both front- and back- end too, so it's no problem pre-hydrating the DOM nodes with a unique key and any other data Maquette would need client-side to match up the elements.

Example at maquette-mapper README:
https://github.com/nextorigin/maquette-mapper

I propose we re-open this ticket so we can find a re-usable pattern, even if it's not included in core.
