### ISSUE TITLE
Projection uses `DOMTokenList#toggle` w/ `force` argument, which is unavailable in IE11 

### ISSUE THREAD

**Issue by jcfranco** [AFASSoftware/maquette#156]
[This helper method](https://github.com/AFASSoftware/maquette/blob/master/src/projection.ts#L305) uses `DOMTokenList#toggle` to toggle classes along with the `force` argument. Unfortunately, this argument is not supported in IE11 and will silently fail.

**Comment by johan-gorter** [comment]
You are right, this is a problem for IE11.

The polyfill provided by maquette polyfills ClassList DOMTokenList properly for IE<11, but it is not triggered for IE11.

The problem only occurs in edge-cases, because toggleClasses is called an odd number of times for classes that should be present and an even number of times for classes that should be removed. Only if classes are removed/added from non-maquette code this would cause a problem.

If this is still a problem for you, we can add a piece from [this polyfill](https://developer.mozilla.org/en-US/docs/Web/API/Element/classList#Polyfill) to maquette's [maquette-polyfills](https://github.com/AFASSoftware/maquette/blob/master/polyfills/maquette-polyfills.js), or if you are using your own polyfills, you can do this yourself.

**Comment by jcfranco** [comment]
If this is considered an edge case, I think it's OK to leave as is. It really came up on our side because a `class` string had duplicate classes (hence the removal).

Thanks and happy holidays!
