### ISSUE TITLE
Firefox vs Chrome speed

### ISSUE THREAD

**Issue by HelloZeroNet** [AFASSoftware/maquette#19]
Hello, I'm looking for a good and fast solution to display large amount of dom elements.

I have created a simple test that similar what I going to do: http://jsfiddle.net/13j1Lfc7/5/

It looks fine in Chrome:
```
jQuery x 3000 = 657ms
Mithril x 3000 = 935ms
Maquette x 3000 = 226ms
```
But not that good in Firefox:
```
jQuery x 3000 = 675ms
Mithril x 3000 = 1098ms
Maquette x 3000 = 1192ms
```

Is there any way to make it faster?

Thanks!

**Comment by johan-gorter** [comment]
Hello,

Sorry for the late reply.

My timings with firefox are:

    jQuery x 3000 = 413ms
    Mithril x 3000 = 585ms
    Maquette x 3000 = 428ms

This makes me believe that you are running adblocker or a similar plugin which significantly slows down firefox.

The reason only maquette is affected by the adblocker this bad, is because other frameworks usually create whole DOM tree 'offscreen' and append it later to the DOM. Maquette appends to the DOM directly to enable easy integration with external widgets like 'Google maps' or 'CKEditor'.

I made a slight change to your setup to create the DOM offscreen: http://jsfiddle.net/13j1Lfc7/6/ My results in Firefox are now:

    jQuery x 3000 = 406ms
    Mithril x 3000 = 572ms
    Maquette x 3000 = 212ms

The effect of an adblocker should also be greatly diminished by using this offscreen technique.

I hope to hear from you if I guessed the adblocker issue correctly and if my change made it faster for you.

**Comment by HelloZeroNet** [comment]
Thanks for the answer! I don't have any active plugin for Firefox, but my cpu is pretty old (core2duo).

Thanks for the tweak, it works for firefox (chrome results are the same):
```
    jQuery x 3000 = 609ms
    Mithril x 3000 = 1164ms
    Maquette x 3000 = 372ms
```

Please let me know if you have other speedup ideas :)

**Comment by johan-gorter** [comment]
What I would suggest is not to make those 3000 dom-trees, but only those who are visible through the viewport. I experimented with this approach and it solves the performance problems, even on mobile devices.

This approach is not easy to build however. You need:

- An onscroll handler on the document, window or your own viewport-element, which calculates which rows need to be visible
- A big empty white element before and after the visible rows
- A fixed row height, hardcoded in Javascript
- To be OK with the fact that screen-readers will not see all of your lines

Hope this helps

**Comment by HelloZeroNet** [comment]
Sure, this is just a benchmark, i'm not going to create 3000 items at once, I just wanted to compare the item creation speed of the options I considering.

Thanks for the tip, it sound like a good idea, but i think the speed still matters if I create and remove items in real-time. Blocking the display for 50ms vs 20ms on scroll probably fairly noticeable.

**Comment by johan-gorter** [comment]
Glad to see that maquette is fastest when it comes to item creation speed!

For your information: In my experiment, scrolling stayed at 60fps, even on mobile devices. Maybe I should publicize the experiment to get some feedback on this.
