### ISSUE TITLE
Returning a VNode without classes and then classes causes an exception

### ISSUE THREAD

**Issue by kitsonk** [AFASSoftware/maquette#42]
Given the following:

```typescript
const projector = createProjector({});
let count = 0;
function render() {
	count++;
	if (count === 1) {
		return h('div');
	}
	return h('div', { classes: { foo: true, bar: true } });
}

projector.append(document.body, render);
projector.scheduleRender();
```

I get the following error:

```
TypeError: Cannot read property 'classes' of undefined
  at updateProperties  <node_modules/maquette/dist/src/maquette.ts:472:43>
  at updateDom  <node_modules/maquette/dist/src/maquette.ts:761:14>
  at Object.update  <node_modules/maquette/dist/src/maquette.ts:779:6>
  at doRender  <node_modules/maquette/dist/src/maquette.ts:1106:21>
```

It generally appears to be related to assuming `previousValue` will actually be available.  It seems that several other properties can run into this as well.

**Comment by johan-gorter** [comment]
One of the reasons why maquette can diff the virtual DOM at such a high speed is because it does not check for missing properties. This means that application developers should comply with three simple rules found [here](http://maquettejs.org/docs/rules.html) and in the [tutorial here](http://maquettejs.org/tutorial/10-distinguishable.html). This means you may not omit the 'classes' property on subsequent renders. You must use one of the following notations:

Using a distinct CSS Selector

    if (count === 1) {
        return h('div');
    }
    return h('div.foo.bar');

Using a disctinct key

    if (count === 1) {
        return h('div', {key: 'count1'});
    }
    return h('div', { classes: { foo: true, bar: true, key: 'otherCount' } });

Or using conditional classes:

    return h('div', { classes: { foo: count !== 1, bar: count !== 1 } });

I hope you will find the rules easy to follow and comprehend. If you have any suggestions about improving the documentation, please let us know.

**Comment by kitsonk** [comment]
Yes, I broke one of the rules!  Sorry...  I think the documentation is fine in this case, as it was explicit and I had read it, I just failed to comprehend the impact of it.
