### ISSUE TITLE
Support HTML string

### ISSUE THREAD

**Issue by yysun** [AFASSoftware/maquette#45]
Is it possible to pass HTML string to maquette for rendering instead of hyperscript?

**Comment by johan-gorter** [comment]
First of all, maquette supports the innerHTML property, which you can put on a VNode, see http://maquettejs.org/docs/typedoc/interfaces/_maquette_.vnodeproperties.html#innerhtml 

For example:

    h('div', {innerHTML: '<b>pre-formatted html</b>'})

It is also possible to use JSX instead of hyperscript all together. For instructions how to get this to work, see: https://medium.com/maquette-news/maquette-2-2-now-supports-jsx-7da7b0a1dc98

I hope this answers your question.

**Comment by yysun** [comment]
Perfect! Thanks for the help.
