### ISSUE TITLE
How can i dynamically add remove event handlers

### ISSUE THREAD

**Issue by tusharmath** [AFASSoftware/maquette#56]
This was the fastest in the virtual dom benchmarks, cheers for that! I was wondering if i could dynamically add and remove event handlers. In the examples i saw you can write inline handlers, but there should be a way to remove them or it would start introducing memory leaks, right?

**Comment by johan-gorter** [comment]
I believe that memory leaks with event handlers was only a problem with IE6 and IE7 when the event-handler also holds a reference to the DOM node. This problem has been fixed with IE8. (historical description of the problem: http://javascript.crockford.com/memory/leak.html)

With maquette, this problem would also normally not occur, because a reference to a real DOM node is typically not needed.

**Comment by tusharmath** [comment]
So if I have a some like this — 
```js
const handleClick = () => console.log('CLICK ME')
h('button', { onclick: handleClick }, [text])
```

Once this `button` isn't available anymore in the DOM, do I not have to remove the clickHandler?

**Comment by johan-gorter** [comment]
That is correct
