### ISSUE TITLE
How can one render a subtree only?

### ISSUE THREAD

**Issue by tusharmath** [AFASSoftware/maquette#68]
If I have a huge dom tree, it would be much better in terms of performance if the patch is applied not on the complete tree but instead directly on the subtree that has changed. This is something react is able to do using components. Is there a way to way to do that using maquette?

**Comment by johan-gorter** [comment]
First of all, maquette can diff DOM trees up to 1000 - 5000 nodes within a single frame on most devices. Are you sure you are dropping frames due to diffing being too slow?

Maquette provides the ability to use caching to skip subtrees from being diffed. See #49 for an example how to use the `createCache` function. Documenting this further is already on our radar, see #60.
