### ISSUE TITLE
`h` helpers

### ISSUE THREAD

**Issue by yosbelms** [AFASSoftware/maquette#83]
Some teams feels comfortable using JavaScript with no transpilation. It would be nice to add helpers to create-element (`h`) favoring pure JS, example:

`h` based code
```js
const h = maquette.h

function renderMaquette() {
  return h('div', [
    h('button', {onclick:load}, ['Load']),
    h('p', [result])
  ]);
}
```

using helpers
```js
const {div, button, p} = maquette.dom

function renderMaquette() {
  return div([
    button({onclick:load}, ['Load']),
    p([result])
  ])
}
```

**Comment by johan-gorter** [comment]
We also experimented with such an approach in https://github.com/AFASResearch/compact-dom Because we wanted to add css classnames to the part before the brackets, we needed a compilation-stage as well. Maybe you can investigate if this suits your needs.

Furthermore, there is nothing stopping you from creating a maquette.dom object yourself which exposes every html5 (and maybe svg) element names. Integrating this into maquette seems like too much weight (because maquette is only 3Kb right now).

**Comment by yosbelms** [comment]
> Furthermore, there is nothing stopping you from creating a maquette.dom object yourself which exposes every html5 (and maybe svg) element names.

Indeed, it is trivial to implement such feature in a separated library, right now my first experimet looks like the following:

```js
import { dom } from './helper'
const {div, li, strong} = dom(['div', 'li', 'strong'])
```
The `dom` creates an object with `h` wrapers on the fly.

Anyways this issue is to throw some light on. However I prefer Maquette to be 3Kb and mantain a small module for these tasks.

**Comment by johan-gorter** [comment]
I hope you will be sharing your experiences with this approach, so more people can discuss it. If you are looking for an efficient implementation on how to create the wrappers for every html element, you can take  a look at an old JQuery plugin that I wrote 4 years ago: https://github.com/johan-gorter/jquery.element/blob/master/jquery.element.js#L98

**Comment by yosbelms** [comment]
Hey @johan-gorter thanks for point me out your jQuery plugin, it is great!. However I've continued with my experiment, finally, I got the culprit, https://github.com/yosbelms/hfactory
